services:
  - type: web
    name: guidance-academy-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_NAME
        value: "Guidance Academy API"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://GuidanceAcademy.vercel.app
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: guidance-academy-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: guidance-academy-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: guidance-academy-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: guidance-academy-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: guidance-academy-db
          property: password

databases:
  - name: guidance-academy-db
    plan: free
    databaseName: guidance_academy
