export type Lang = 'en' | 'am';

export const dict = {
  en: {
    nav: {
      home: 'Home', about: 'About Us', register: 'Register', login: 'Login',
      logout: 'Logout', admin: 'Admin Panel', dashboard: 'Dashboard', switchLang: 'አማርኛ',
    },
    hero: {
      badge: 'NOW OPEN FOR REGISTRATION',
      title: 'SUMMER COURSE',
      sub: 'Basic English Grammar, Speaking & Presentation Skills Course',
      date: 'Classes start: July 01 / 11 / 2018 E.C.',
      cta: 'Register Now — It\'s Free',
      ctaSub: 'Login to your account',
    },
    bullets: ['⚡ Limited seats — register fast!', '🎓 For Junior & High School students'],
    info: {
      sectionTitle: 'Course Info',
      cards: [
        { icon: '📞', label: 'Contact Us',   val: '0909918195 / 0915260722' },
        { icon: '👤', label: 'Trainer',       val: 'Suleyman Abdu' },
        { icon: '📍', label: 'Location',      val: 'Harbu High School, Harbu' },
        { icon: '🕐', label: 'Start Date',    val: 'July 01/11/2018 E.C.' },
        { icon: '💰', label: 'Course Fee',    val: 'Contact us for pricing' },
        { icon: '🌐', label: 'Also Online',   val: 'GuidanceAcademy.vercel.app' },
      ],
      whatYouLearn: 'What You Will Learn',
      topics: [
        { icon: '📖', t: 'English Grammar', s: 'From basics to advanced sentence structures' },
        { icon: '🎤', t: 'Speaking Skills', s: 'Confidence building with daily practice' },
        { icon: '🖥️', t: 'Presentation', s: 'How to present ideas clearly and professionally' },
        { icon: '✍️', t: 'Writing', s: 'Structured writing and composition techniques' },
      ],
      whoFor: 'Who Is This For?',
      audience: [
        'Grade 7–12 students wanting to improve English',
        'Students preparing for exams',
        'Anyone who wants to speak confidently',
        'Adults and professionals are also welcome',
      ],
    },
    about: {
      title: 'About Us',
      sub: 'Learn about Guidance Language & Skills Academy',
      mission: 'Our Mission',
      missionText: 'To empower students and young professionals in Ethiopia to communicate with confidence in English — opening doors to education, career growth, and global opportunity.',
      vision: 'Our Vision',
      visionText: 'To become the leading language and skills training academy in Ethiopia, known for transforming lives through quality English education.',
      trainerTitle: 'Meet Your Trainer',
      trainerName: 'Suleyman Abdu',
      trainerRole: 'Founder & Lead Trainer',
      trainerBio: 'Suleyman Abdu is a dedicated English language trainer with years of experience helping students build confidence and fluency. He founded Guidance Language & Skills Academy with a vision to make quality English education accessible to every Ethiopian student.',
      whyUs: 'Why Choose Us?',
      reasons: [
        { icon: '🏆', t: 'Proven Results',      s: 'Hundreds of students have improved their English with us' },
        { icon: '👨‍🏫', t: 'Expert Trainer',    s: 'Qualified and experienced English instructor' },
        { icon: '📍', t: 'Convenient Location', s: 'Located at Harbu High School in Harbu' },
        { icon: '🌍', t: 'Bilingual Support',   s: 'Instruction available in English and Amharic' },
        { icon: '💡', t: 'Practical Focus',     s: 'Real-world speaking, grammar, and presentation skills' },
        { icon: '📱', t: 'Online Access',       s: 'Study materials available online at any time' },
      ],
      contact: 'Get In Touch',
      phones: ['0909918195', '0915260722'],
      address: 'Harbu High School, Harbu, Ethiopia',
      website: 'GuidanceAcademy.vercel.app',
      tagline: '"Speak with Confidence, Succeed with Skills."',
    },
    reg: {
      stepLabels: ['Identity', 'Contact', 'Motivation'],
      stepOf: (s: number) => `Step ${s} of 3`,
      nameEn: 'Full Name (English)', nameEnPh: 'e.g. Suleyman Abdu',
      nameAm: 'Full Name (Amharic)', nameAmPh: 'Enter your full name',
      phone: 'Phone Number', phonePh: '09XXXXXXXX',
      grade: 'Grade / Level',
      gradeOpts: [
        { v: '', l: 'Select…' }, { v: 'grade7', l: 'Grade 7–8 (Junior)' },
        { v: 'grade9', l: 'Grade 9–10 (Secondary)' },
        { v: 'grade11', l: 'Grade 11–12 (Preparatory)' }, { v: 'other', l: 'Other / Adult' },
      ],
      purpose: 'Why do you want to learn English?', purposePh: 'Share your goal…',
      referral: 'Where did you hear about us?',
      refOpts: [
        { v: '', l: 'Select one…' }, { v: 'telegram', l: 'Telegram' },
        { v: 'friends', l: 'Friends' }, { v: 'banner', l: 'Banner / Flyer' }, { v: 'other', l: 'Other' },
      ],
      next: 'Continue', back: 'Back', submit: 'Register Now', submitting: 'Registering…',
      required: 'This field is required.',
      phoneErr: 'Enter a valid Ethiopian phone number (09... or 07...).',
    },
    setup: {
      title: '🎉 Registration Successful!',
      sub: 'Create your account to access your student dashboard.',
      usernameLabel: 'Username',
      usernameSub: "Default: your name + first letter of father's name. You can edit it.",
      usernamePh: 'e.g. suleymanA',
      passwordLabel: 'Password',
      passwordPh: 'Minimum 8 characters',
      confirmLabel: 'Confirm Password',
      confirmPh: 'Re-enter your password',
      submit: 'Create Account & Continue',
      submitting: 'Creating account…',
      usernameErr: 'Username is already taken.',
      passwordMismatch: 'Passwords do not match.',
      passwordShort: 'Password must be at least 8 characters.',
    },
    home: {
      welcome: 'Welcome back',
      announcements: 'Announcements',
      news: 'Latest News',
      tips: 'Study Tips',
      noPost: 'No posts yet. Check back soon!',
      postedBy: 'Posted by Admin',
    },
    admin: {
      dashboard: 'Admin Dashboard', students: 'Registered Students', posts: 'Manage Posts',
      totalStudents: 'Total Students', pending: 'Pending', approved: 'Approved',
      newPost: 'New Post', search: 'Search by name or phone…',
      filterAll: 'All', filterPending: 'Pending', filterApproved: 'Approved', filterRejected: 'Rejected',
      colName: 'Name', colPhone: 'Phone', colGrade: 'Grade', colReferral: 'Source',
      colStatus: 'Status', colDate: 'Registered', colActions: 'Actions',
      approve: 'Approve', reject: 'Reject', delete: 'Delete', view: 'View',
      postTitleEn: 'Title (English)', postTitleAm: 'Title (Amharic)',
      postBodyEn: 'Content (English)', postBodyAm: 'Content (Amharic)',
      postType: 'Post Type', postPublish: 'Publish immediately',
      savePost: 'Save Post', updatePost: 'Update Post',
      confirmDelete: 'Delete this student record?', confirmDeletePost: 'Delete this post?',
      publish: 'Publish', unpublish: 'Unpublish', edit: 'Edit',
    },
    login: {
      title: 'Welcome Back', sub: 'Sign in to your account',
      username: 'Username', password: 'Password',
      submit: 'Sign In', submitting: 'Signing in…',
      noAccount: 'New student? Register here',
      wrongCreds: 'Invalid username or password.',
    },
    contact: {
      title: 'Contact Us',
      sub: 'Get in touch with Guidance Academy',
      getInTouch: 'Get In Touch',
      reachOut: 'We\'d love to hear from you! Reach out via phone, email, or SMS.',
      yourName: 'Your Name',
      yourNamePh: 'Enter your name',
      message: 'Your Message',
      messagePh: 'Type your message here...',
      sendEmail: 'Send Email',
      sendSMS: 'Send SMS',
      callUs: 'Call Us',
      emailUs: 'Email Us',
      textUs: 'Text Us',
      location: 'Our Location',
      emailLabel: 'Email',
      phoneLabel: 'Phone',
      addressLabel: 'Address',
    },
    footer: {
      contact: 'Contact Us', trainer: 'Trainer', address: 'Address', online: 'Register Online',
      trainerName: 'Suleyman Abdu', addressVal: 'Harbu High School, Harbu',
      tagline: 'Speak with Confidence, Succeed with Skills.',
      rights: '© 2024 Guidance Language & Skills Academy',
      links: { home: 'Home', about: 'About Us', register: 'Register', login: 'Login', contact: 'Contact' },
    },
  },

  am: {
    nav: {
      home: 'መነሻ', about: 'ስለ እኛ', register: 'ይመዝገቡ', login: 'ግባ',
      logout: 'ውጣ', admin: 'አስተዳዳሪ', dashboard: 'ዳሽቦርድ', switchLang: 'English',
    },
    hero: {
      badge: 'አሁን ለመመዝገብ ክፍት ነን!',
      title: 'የበጋ ክፍተት',
      sub: 'መሰረታዊ የአንግሊዘኛ ሰዋስው፣ ተናጋሪነት እና አቀራረብ ክህሎት ኮርስ',
      date: 'ክፍሎች ከጁላይ 01/11/2018 ዓ.ም. ይጀምራሉ',
      cta: 'አሁን ይመዝገቡ — ነፃ ነው',
      ctaSub: 'ወደ መለያዎ ይግቡ',
    },
    bullets: ['⚡ የተወሰኑ ቦታዎች ብቻ — ፈጠን ይመዝገቡ!', '🎓 ለጁኒየር እና ሁለተኛ ደረጃ ተማሪዎች'],
    info: {
      sectionTitle: 'የኮርስ መረጃ',
      cards: [
        { icon: '📞', label: 'ያናግሩን',       val: '0909918195 / 0915260722' },
        { icon: '👤', label: 'አሰልጣኝ',       val: 'ሱለይማን አብዱ' },
        { icon: '📍', label: 'አድራሻ',        val: 'ሃርቡ ሁለተኛ ደረጃ ት/ቤት፣ ሃርቡ' },
        { icon: '🕐', label: 'የጅምር ቀን',    val: 'ጁላይ 01/11/2018 ዓ.ም.' },
        { icon: '💰', label: 'የኮርስ ክፍያ',  val: 'ለዋጋ ያናግሩን' },
        { icon: '🌐', label: 'በ Online ደግሞ', val: 'GuidanceAcademy.vercel.app' },
      ],
      whatYouLearn: 'ምን ይማሩ?',
      topics: [
        { icon: '📖', t: 'የእንግሊዘኛ ሰዋስው', s: 'ከመሰረቱ ጀምሮ ወደ ከፍተኛ ደረጃ' },
        { icon: '🎤', t: 'የተናጋሪነት ክህሎት', s: 'በዕለት ልምምድ መተማመን' },
        { icon: '🖥️', t: 'አቀራረብ ክህሎት',   s: 'ሃሳቦችን ግልፅ እና ሙያዊ አቀራረብ' },
        { icon: '✍️', t: 'የጽሁፍ ክህሎት',    s: 'መዋቅራዊ ጽሁፍ እና ቅንብር' },
      ],
      whoFor: 'ለማን ነው?',
      audience: [
        'ክፍል 7–12 ተማሪዎች አንግሊዘኛ ለማሻሻል',
        'ፈተናዎችን ለሚዘጋጁ ተማሪዎች',
        'በልበ ሙሉነት መናገር ለሚፈልጉ',
        'ጎልማሶች እና ሙያተኞችም ይቀበላሉ',
      ],
    },
    about: {
      title: 'ስለ እኛ',
      sub: 'ጋይዳንስ ቋንቋ እና ክህሎት አካዴሚን ይወቁ',
      mission: 'ዓላማችን',
      missionText: 'ኢትዮጵያ ውስጥ ተማሪዎች እና ወጣት ሙያተኞች በአንግሊዘኛ በልበ ሙሉነት እንዲናገሩ ማብቃት — ወደ ትምህርት፣ ሙያ ዕድገት እና ዓለም አቀፍ እድሎች ደጃፍ መክፈት።',
      vision: 'ራዕያችን',
      visionText: 'ጥራት ያለው የአንግሊዘኛ ትምህርት ሕይወትን በመቀየር ኢትዮጵያ ውስጥ ዋነኛ የቋንቋ እና ክህሎት ማሰልጠኛ አካዴሚ መሆን።',
      trainerTitle: 'አሰልጣኝዎን ይወቁ',
      trainerName: 'ሱለይማን አብዱ',
      trainerRole: 'መስራች እና ዋና አሰልጣኝ',
      trainerBio: 'ሱለይማን አብዱ ተማሪዎች እምነት እና ብቃት እንዲኖራቸው በማድረግ ዓመታዊ ልምድ ያለው ቆራጥ የእንግሊዘኛ ቋንቋ አሰልጣኝ ነው። ጥራት ያለው የእንግሊዘኛ ትምህርት ለእያንዳንዱ ኢትዮጵያዊ ተማሪ ተደራሽ ለማድረግ ቅን ፍላጎቱ ጋይዳንስ ቋንቋ እና ክህሎት አካዴሚን አቋቋመ።',
      whyUs: 'ለምን እኛን ይምረጡ?',
      reasons: [
        { icon: '🏆', t: 'የተረጋገጡ ውጤቶች',   s: 'በመቶዎች የሚቆጠሩ ተማሪዎች አንግሊዘኛቸውን አሻሽለዋል' },
        { icon: '👨‍🏫', t: 'ባለሙያ አሰልጣኝ',   s: 'ብቁ እና ልምድ ያለው የእንግሊዘኛ አስተማሪ' },
        { icon: '📍', t: 'ምቹ ቦታ',           s: 'ሃርቡ ሁለተኛ ደረጃ ት/ቤት' },
        { icon: '🌍', t: 'ሁለት ቋንቋ ድጋፍ',   s: 'ትምህርት በእንግሊዘኛ እና አማርኛ' },
        { icon: '💡', t: 'ተግባራዊ ትኩረት',    s: 'ዕለታዊ ንግግር፣ ሰዋስው እና አቀራረብ' },
        { icon: '📱', t: 'Online ተደራሽ',    s: 'ትምህርት ቁሳቁሶች በማንኛውም ጊዜ' },
      ],
      contact: 'ያናግሩን',
      phones: ['0909918195', '0915260722'],
      address: 'ሃርቡ ሁለተኛ ደረጃ ት/ቤት፣ ሃርቡ፣ ኢትዮጵያ',
      website: 'GuidanceAcademy.vercel.app',
      tagline: '"በልበ ሙሉነት ተናገሩ፣ በክህሎት ስኬታማ ይሁኑ።"',
    },
    reg: {
      stepLabels: ['መታወቂያ', 'ግንኙነት', 'ዓላማ'],
      stepOf: (s: number) => `ደረጃ ${s} ከ 3`,
      nameEn: 'ሙሉ ስም በእንግሊዘኛ', nameEnPh: 'ለምሳሌ Suleyman Abdu',
      nameAm: 'ሙሉ ስም በአማርኛ', nameAmPh: 'ሙሉ ስምዎን ያስገቡ',
      phone: 'ስልክ ቁጥር', phonePh: '09XXXXXXXX',
      grade: 'ክፍል / ደረጃ',
      gradeOpts: [
        { v: '', l: 'ይምረጡ…' }, { v: 'grade7', l: 'ክፍል 7–8 (ጁኒየር)' },
        { v: 'grade9', l: 'ክፍል 9–10 (ሁለተኛ ደረጃ)' },
        { v: 'grade11', l: 'ክፍል 11–12 (ፕሬፓራቶሪ)' }, { v: 'other', l: 'ሌላ / ጎልማሳ' },
      ],
      purpose: 'እንግሊዘኛ መማር ለምን ፈለጉ?', purposePh: 'ዓላማዎን ያስቀምጡ…',
      referral: 'ስለ እኛ ከየት ሰሙ?',
      refOpts: [
        { v: '', l: 'ይምረጡ…' }, { v: 'telegram', l: 'ቴሌግራም' },
        { v: 'friends', l: 'ጓደኞች' }, { v: 'banner', l: 'ባነር / ብሮሹር' }, { v: 'other', l: 'ሌላ' },
      ],
      next: 'ቀጥል', back: 'ተመለስ', submit: 'አሁን ይመዝገቡ', submitting: 'እየተመዘገበ ነው…',
      required: 'ይህ መስክ ያስፈልጋል።',
      phoneErr: 'ትክክለኛ የኢትዮጵያ ስልክ ቁጥር ያስገቡ (09... ወይም 07...).',
    },
    setup: {
      title: '🎉 ምዝገባዎ ተሳክቷል!',
      sub: 'መለያዎን ይፍጠሩ — የተማሪ ዳሽቦርድዎን ለመጠቀም።',
      usernameLabel: 'የተጠቃሚ ስም',
      usernameSub: 'ነባሪ: ስምዎ + የአባት ስም የመጀመሪያ ፊደል። ሊቀይሩት ይችላሉ።',
      usernamePh: 'ለምሳሌ suleymanA',
      passwordLabel: 'ምስጢር ቁጥር',
      passwordPh: 'ቢያንስ 8 ቁምፊዎች',
      confirmLabel: 'ምስጢር ቁጥር ያረጋግጡ',
      confirmPh: 'ምስጢር ቁጥርዎን ደጋግሙ',
      submit: 'መለያ ፍጠር እና ቀጥል',
      submitting: 'መለያ እየተፈጠረ ነው…',
      usernameErr: 'ይህ የተጠቃሚ ስም ተወስዷል።',
      passwordMismatch: 'ምስጢር ቁጥሮቹ አይዛሙም።',
      passwordShort: 'ምስጢር ቁጥር ቢያንስ 8 ቁምፊዎች መሆን አለበት።',
    },
    home: {
      welcome: 'እንኳን ደህና መጡ',
      announcements: 'ማስታወቂያዎች',
      news: 'የቅርብ ጊዜ ዜና',
      tips: 'የጥናት ምክሮች',
      noPost: 'ምንም ልጥፍ የለም። ብዙም ሳይቆይ ይፈትሹ!',
      postedBy: 'ቀርቦ ያለው በአስተዳዳሪ',
    },
    admin: {
      dashboard: 'የአስተዳዳሪ ዳሽቦርድ', students: 'የተመዘገቡ ተማሪዎች', posts: 'ልጥፎችን አስተዳድር',
      totalStudents: 'ጠቅላላ ተማሪዎች', pending: 'በመጠባበቅ ላይ', approved: 'ጸድቋል',
      newPost: 'አዲስ ልጥፍ', search: 'በስም ወይም ስልክ ይፈልጉ…',
      filterAll: 'ሁሉም', filterPending: 'በመጠባበቅ', filterApproved: 'ጸድቋል', filterRejected: 'ተቀባይነት አላገኘም',
      colName: 'ስም', colPhone: 'ስልክ', colGrade: 'ክፍል', colReferral: 'ምንጭ',
      colStatus: 'ሁኔታ', colDate: 'ተመዝግቧል', colActions: 'ድርጊቶች',
      approve: 'አጽድቅ', reject: 'ውደድ', delete: 'ሰርዝ', view: 'ይመልከቱ',
      postTitleEn: 'ርዕስ (እንግሊዘኛ)', postTitleAm: 'ርዕስ (አማርኛ)',
      postBodyEn: 'ይዘት (እንግሊዘኛ)', postBodyAm: 'ይዘት (አማርኛ)',
      postType: 'የልጥፍ አይነት', postPublish: 'ወዲያውኑ አሳትም',
      savePost: 'ልጥፍ ያስቀምጡ', updatePost: 'ልጥፍ ያዘምኑ',
      confirmDelete: 'ይህን የተማሪ መዝገብ ይሰርዙ?', confirmDeletePost: 'ይህን ልጥፍ ይሰርዙ?',
      publish: 'አሳትም', unpublish: 'ሰርዝ ህትመት', edit: 'አርም',
    },
    login: {
      title: 'እንኳን ደህና መጡ', sub: 'ወደ መለያዎ ይግቡ',
      username: 'የተጠቃሚ ስም', password: 'ምስጢር ቁጥር',
      submit: 'ግባ', submitting: 'እየተሰናዳ ነው…',
      noAccount: 'አዲስ ተማሪ? እዚህ ይመዝገቡ',
      wrongCreds: 'ያልተሳካ የተጠቃሚ ስም ወይም ምስጢር ቁጥር።',
    },
    contact: {
      title: 'ያናግሩን',
      sub: 'ከጋይዳንስ አካዴሚ ጋር ይገናኙ',
      getInTouch: 'ያናግሩን',
      reachOut: 'ከእርስዎ መስማት እንፈልጋለን! በስልክ፣ ኢሜይል ወይም SMS ያግኙን።',
      yourName: 'ስምዎ',
      yourNamePh: 'ስምዎን ያስገቡ',
      message: 'መልእክትዎ',
      messagePh: 'መልእክትዎን እዚህ ይጻፉ...',
      sendEmail: 'ኢሜይል ይላኩ',
      sendSMS: 'SMS ይላኩ',
      callUs: 'ይደውሉልን',
      emailUs: 'ኢሜይል ይላኩልን',
      textUs: 'መልእክት ይላኩልን',
      location: 'አድራሻችን',
      emailLabel: 'ኢሜይል',
      phoneLabel: 'ስልክ',
      addressLabel: 'አድራሻ',
    },
    footer: {
      contact: 'ያናግሩን', trainer: 'አሰልጣኝ', address: 'አድራሻ', online: 'በ Online ይመዝገቡ',
      trainerName: 'ሱለይማን አብዱ', addressVal: 'ሃርቡ ሁለተኛ ደረጃ ት/ቤት፣ ሃርቡ',
      tagline: 'በልበ ሙሉነት ተናገሩ፣ በክህሎት ስኬታማ ይሁኑ።',
      rights: '© 2024 ጋይዳንስ ቋንቋ እና ክህሎት አካዴሚ',
      links: { home: 'መነሻ', about: 'ስለ እኛ', register: 'ይመዝገቡ', login: 'ግባ', contact: 'ያናግሩን' },
    },
  },
};
